apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-finance-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-finance-management
  template:
    metadata:
      labels:
        app: personal-finance-management
    spec:
      containers:
      - name: personal-finance-management
        image: shaybar6/personal-finance-management:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: aws_default_region
