name: Deploy to EKS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks --region eu-west-1 update-kubeconfig --name my-cluster

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic my-secret \
          --from-literal=aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --from-literal=aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --from-literal=aws_default_region=${{ secrets.AWS_DEFAULT_REGION }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/app-deployment.yaml
        kubectl apply -f k8s/app-service.yaml
