name: Deploy to EKS

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted
    if: |
      github.event_name == 'push' || (
        contains(github.event.head_commit.message, 'src/') || 
        contains(github.event.head_commit.message, 'Dockerfile')
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t shaybar6/personal-finance-management:${{ github.sha }} .

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push shaybar6/personal-finance-management:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build  # Only run if build completes successfully
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks --region eu-west-1 update-kubeconfig --name my-cluster

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      # Update the deployment YAML with the unique tag
      - name: Update Deployment YAML
        run: |
          sed -i "s|TAG_PLACEHOLDER|${{ github.sha }}|g" k8s/app-deployment.yaml

      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml
